version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Password23"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - sqlserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=Hack
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Password23
      SPRING_JPA_HIBERNATE_DDL_AUTO: none  # Flyway cuida do schema
    ports:
      - "8080:8080"
